
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usrlab06
 */
public class FormMenu extends javax.swing.JFrame {

    DefaultTableModel model;

    public FormMenu() {
        initComponents();
        setLocationRelativeTo(null);
        jComboEscolaridade.setSelectedIndex(-1);
        model = ((DefaultTableModel) jTableConsulta.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameCadastro = new javax.swing.JFrame();
        jComboEscolaridade = new javax.swing.JComboBox<>();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEscolaridade = new javax.swing.JLabel();
        jFrameConsulta = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jFrameConsultaIndividual = new javax.swing.JFrame();
        jLabelNomeConsulta = new javax.swing.JLabel();
        jLabelEmailConsulta = new javax.swing.JLabel();
        jLabelEscolaridadeConsulta = new javax.swing.JLabel();
        jButtonConsulta = new javax.swing.JButton();
        jButtonCadastro = new javax.swing.JButton();

        jFrameCadastro.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameCadastro.setTitle("UFNSYS: Cadastro");
        jFrameCadastro.setResizable(false);
        jFrameCadastro.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFrameCadastroWindowClosed(evt);
            }
        });

        jComboEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Fundamental", "Ensino Médio", "Ensino Superior" }));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelNome.setText("Nome:");

        jLabelEmail.setText("Email:");

        jLabelEscolaridade.setText("Escolaridade:");

        javax.swing.GroupLayout jFrameCadastroLayout = new javax.swing.GroupLayout(jFrameCadastro.getContentPane());
        jFrameCadastro.getContentPane().setLayout(jFrameCadastroLayout);
        jFrameCadastroLayout.setHorizontalGroup(
            jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome)
                    .addComponent(jTextFieldEmail)
                    .addGroup(jFrameCadastroLayout.createSequentialGroup()
                        .addGroup(jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelEscolaridade)
                            .addComponent(jComboEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar)))
                .addContainerGap())
        );
        jFrameCadastroLayout.setVerticalGroup(
            jFrameCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEscolaridade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addContainerGap())
        );

        jFrameConsulta.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameConsulta.setTitle("UFNSYS: Consulta");
        jFrameConsulta.setResizable(false);
        jFrameConsulta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFrameConsultaWindowClosed(evt);
            }
        });

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Escolaridade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        javax.swing.GroupLayout jFrameConsultaLayout = new javax.swing.GroupLayout(jFrameConsulta.getContentPane());
        jFrameConsulta.getContentPane().setLayout(jFrameConsultaLayout);
        jFrameConsultaLayout.setHorizontalGroup(
            jFrameConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jFrameConsultaLayout.setVerticalGroup(
            jFrameConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jFrameConsultaIndividual.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameConsultaIndividual.setTitle("UFNSYS: Consulta Individual");
        jFrameConsultaIndividual.setResizable(false);

        jLabelNomeConsulta.setText("Nome:");

        jLabelEmailConsulta.setText("Email:");

        jLabelEscolaridadeConsulta.setText("Escolaridade:");

        javax.swing.GroupLayout jFrameConsultaIndividualLayout = new javax.swing.GroupLayout(jFrameConsultaIndividual.getContentPane());
        jFrameConsultaIndividual.getContentPane().setLayout(jFrameConsultaIndividualLayout);
        jFrameConsultaIndividualLayout.setHorizontalGroup(
            jFrameConsultaIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameConsultaIndividualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameConsultaIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeConsulta)
                    .addComponent(jLabelEmailConsulta)
                    .addComponent(jLabelEscolaridadeConsulta))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jFrameConsultaIndividualLayout.setVerticalGroup(
            jFrameConsultaIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameConsultaIndividualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmailConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEscolaridadeConsulta)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UFNSYS: Menu");
        setResizable(false);

        jButtonConsulta.setText("Consulta");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jButtonCadastro.setText("Cadastro");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButtonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        this.dispose();
        jFrameConsulta.setVisible(true);
        jFrameConsulta.setSize(800, 600);
        jFrameConsulta.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
        this.dispose();
        jFrameCadastro.setVisible(true);
        jFrameCadastro.setSize(400, 300);
        jFrameCadastro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonCadastroActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        if (verificarCampos() == false) {
            Pessoa pessoa = new Pessoa();
            pessoa.setNome(jTextFieldNome.getText());
            pessoa.setEmail(jTextFieldEmail.getText());
            pessoa.setEscolaridade(jComboEscolaridade.getSelectedItem().toString());

            model.addRow(new String[]{pessoa.getNome(), pessoa.getEmail(), pessoa.getEscolaridade()});
            limparCampos();
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jFrameCadastroWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameCadastroWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_jFrameCadastroWindowClosed

    private void jFrameConsultaWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameConsultaWindowClosed
        this.setVisible(true);
    }//GEN-LAST:event_jFrameConsultaWindowClosed

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked
        jFrameConsultaIndividual.setVisible(true);
        jFrameConsultaIndividual.setSize(400, 300);
        jFrameConsultaIndividual.setLocationRelativeTo(null);

        jLabelNomeConsulta.setText("Nome: " + jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 0));
        jLabelEmailConsulta.setText("Email: " + jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 1));
        jLabelEscolaridadeConsulta.setText("Escolaridade: " + jTableConsulta.getValueAt(jTableConsulta.getSelectedRow(), 2));

    }//GEN-LAST:event_jTableConsultaMouseClicked

    public void limparCampos() {
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jComboEscolaridade.setSelectedIndex(-1);
    }

    public boolean verificarCampos() {
        boolean erro = false;

        if ((jTextFieldNome.getText().isEmpty()) || (jTextFieldEmail.getText().isEmpty()) || (jComboEscolaridade.getSelectedIndex() == -1)) {
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos corretamente.", "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            erro = true;
        }
        return erro;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JComboBox<String> jComboEscolaridade;
    private javax.swing.JFrame jFrameCadastro;
    private javax.swing.JFrame jFrameConsulta;
    private javax.swing.JFrame jFrameConsultaIndividual;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailConsulta;
    private javax.swing.JLabel jLabelEscolaridade;
    private javax.swing.JLabel jLabelEscolaridadeConsulta;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
