
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usrlab06
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEstadoCivil = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEscolaridade = new javax.swing.JLabel();
        jCheckFundamental = new javax.swing.JCheckBox();
        jCheckMedio = new javax.swing.JCheckBox();
        jCheckSuperior = new javax.swing.JCheckBox();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jRadioSolteiro = new javax.swing.JRadioButton();
        jRadioCasado = new javax.swing.JRadioButton();
        jButtonCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo RH: Cadastro de Pessoa");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("UFN Systems");
        jLabelTitulo.setAlignmentY(0.0F);

        jLabelNome.setText("Nome do Colaborador:");

        jLabelEmail.setText("Email:");

        jLabelEscolaridade.setText("Escolaridade:");

        jCheckFundamental.setText("Ensino Fundamental");

        jCheckMedio.setText("Ensino Médio");

        jCheckSuperior.setText("Ensino Superior");

        jLabelEstadoCivil.setText("Estado Civil:");

        buttonGroupEstadoCivil.add(jRadioSolteiro);
        jRadioSolteiro.setText("Solteiro");

        buttonGroupEstadoCivil.add(jRadioCasado);
        jRadioCasado.setText("Casado");

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckSuperior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEscolaridade)
                                    .addComponent(jCheckFundamental)
                                    .addComponent(jCheckMedio))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioCasado)
                                    .addComponent(jLabelEstadoCivil)
                                    .addComponent(jRadioSolteiro))))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jTextFieldEmail)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEscolaridade)
                    .addComponent(jLabelEstadoCivil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFundamental)
                    .addComponent(jRadioSolteiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckMedio)
                    .addComponent(jRadioCasado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckSuperior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Colaborador colaborador = new Colaborador();
        
        colaborador.setNome(jTextFieldNome.getText());
        colaborador.setEmail(jTextFieldEmail.getText());
        if (jCheckFundamental.isSelected()) colaborador.setEscolaridade(jCheckFundamental.getText());
        if (jCheckMedio.isSelected()) colaborador.setEscolaridade(jCheckMedio.getText());
        if (jCheckSuperior.isSelected()) colaborador.setEscolaridade(jCheckSuperior.getText());
        
        if (jRadioSolteiro.isSelected()) colaborador.setEstadoCivil(jRadioSolteiro.getText()); 
        else if (jRadioCasado.isSelected()) colaborador.setEstadoCivil(jRadioCasado.getText());
        else colaborador.setEstadoCivil("");
        
        Method method = new Method();
        
        if (method.verificarCampos(colaborador) == true) {
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos corretamente.", "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            method.limparFrame(this);
        } else {
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!" 
                + "\n\nNome: " + colaborador.getNome() 
                + "\nEmail: " + colaborador.getEmail()
                + "\nEscolaridade: " + colaborador.getEscolaridade()
                + "\nEstado Civil: " + colaborador.getEstadoCivil(), "Mensagem", JOptionPane.INFORMATION_MESSAGE
            );
            method.limparFrame(this);
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    public void setButtonGroupEstadoCivil() {
        buttonGroupEstadoCivil.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupEstadoCivil;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JCheckBox jCheckFundamental;
    private javax.swing.JCheckBox jCheckMedio;
    private javax.swing.JCheckBox jCheckSuperior;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEscolaridade;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JRadioButton jRadioCasado;
    private javax.swing.JRadioButton jRadioSolteiro;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
